### ISSUE TITLE
Image don´t  exist in quay.io.

### ISSUE THREAD

**Issue by marcokonsultex** [AlfrescoLabs/alfresco-enterprise-docker#2]
Hi Angel,

I'm using your project for the enterprise and when it tries to fetch the image from the Control Center, it generates an error stating that said image does not exist.

Are there any changes or configurations I need to make to be able to successfully download all the images and create the container?

I have a user on NEXUS and quay.io and I configure a variable on the OS using export.

**Comment by aborroy** [comment]
Are you able to pull the Docker Image from command line?

```bash
docker pull quay.io/alfresco/alfresco-control-center:8.4.0
```

**Comment by marcokonsultex** [comment]
Thanks Angel.

That's ok. The name of image in docker-compose was different. Then I change and that's ok.
